#!/usr/bin/env node
'use strict';

let execSync = require('child_process').execSync;
let extend = require('util')._extend;
let repository = require('../package.json').repository;
repository = repository.url ? repository.url : repository;
// ensure we have an https url to the repo
repository = repository.replace(/.+(?=github[.]com)/, 'https://');
// omit '.git' at the end of the repo url
repository = repository.replace(/[.]git$/, '');

execSync("./node_modules/.bin/release", {
  stdio: 'inherit',
  // in case pre-commit hook to prevent committing to master is in place
  env: extend({ 'ALLOW_MASTER': 1 }, process.env)
});

let tags = execSync("git tag -l --sort v:refname").toString().trim().split('\n').filter(function(tag) {
  return tag[0] === 'v';
});
let prevVersion = tags[tags.length - 2];
let newVersion = tags[tags.length - 1];

let changelog = execSync(`./dev/changelog ${prevVersion} ${newVersion}`, {
  stdio: [ 'pipe', 'pipe', process.stderr ]
}).toString();

console.log(`\nVersion tagged! Now paste changelog into ${repository}/releases/edit/${newVersion}:\n`);
console.log(changelog);
